### ISSUE TITLE
Determinism for rollback netcode

### ISSUE THREAD

**Issue by logixworx** [Anders429/brood#175]
Could brood be used for deterministic rollback netcode? Thanks.

**Comment by Anders429** [comment]
As far as determinism goes, all methods on `World` are indeed deterministic, assuming the mutable queries and systems you run on the `World` are themselves deterministic. A single instance of a `World` can be thought of as a "state" at any given time in your program, and running a deterministic `System` (or a `Schedule` made up of many deterministic `System`s) will always result in the same new state. 

For the rollback netcode part of your question, `brood` itself does not provide any logic for rollback (although I don't think any ECS library in the Rust ecosystem has that built in). But, I think it does have the some of the building blocks to make it work. As I already said, `World`s are deterministic. They are also `Clone`able, assuming the components stored within the `World` also implement `Clone` (see [here](https://docs.rs/brood/latest/brood/struct.World.html#impl-Clone-for-World%3CR%3E)). This means it should be possible to create multiple copies of your game state, so that you can store the state for previous frames and roll forward from one of them if needed. Note that if you actually use a ring buffer of `World`s, I would recommend cloning into them using [`Clone::clone_from()`](https://docs.rs/brood/latest/brood/struct.World.html#method.clone_from) to reuse previous allocations.  

I think it's doable, although nothing is specifically geared toward rollback netcode. Performance-wise, I don't think there will be much problem, as `brood` is on-par with other ECS implementations.

Hope that helps!
