### ISSUE TITLE
Production Ready

### ISSUE THREAD

**Issue by logixworx** [Anders429/brood#186]
Would you say brood is production ready?

**Comment by Anders429** [comment]
That's a pretty big question, but I'll try to answer it as concisely as I can. Here goes:

`brood` is totally usable as an ECS library. It is more than just a "proof of concept"; `brood` was designed from the beginning with performance, scalability, and soundness in mind. The entire public API is documented and the crate is well tested. Benchmarks have shown `brood` to have on-par or better performance compared to other ECS libraries in the Rust ecosystem. Querying and scheduling are set up to take full advantage of parallel iteration (with both inner and outer joins) through interfacing with [`rayon`](https://crates.io/crates/rayon), allowing you to iterate tens of thousands of entities very quickly (well within one frame, according to benchmarks I have run).

A few things I think `brood` has going for it over other ECS solutions in the Rust ecosystem:
- Use of heterogeneous lists (often called HLists) allows for inserting and querying lists of components that are arbitrarily long. Other ECS solutions often limit you to at most 8, 16, or sometimes 24 component views at a time during querying, which can be frustrating as your project grows in scale. There is no limit to the number of components that can be viewed here (although you may need to bump up the type `recursion_limit` if you try to view more than 128 at once).
- The query system is, in my opinion, very clear and expressive. It feels straightforward defining what views you want to have on your components.
- As many things are pushed to compile-time as possible, including reordering of components before storage or viewing. Even construction of stages for a `Schedule` is done at compile time through some HList tricks. This means that the run-time overhead is minimal.

The two things that make me hesitant to outright say `brood` is "production ready", however, are the absence of certain features and the stability of the API. 

As I said above, `brood` is a strong ECS that I believe is completely usable at this time. However, in my own use of it I've come across some small pain points. For example:
- There is currently no way to look up entries for other entities during query iteration, making inter-entity relationships a bit more difficult. It doesn't make them impossible by any means, it just makes them a bit less convenient than they could be. See #185 for the progress being made on that.
- There is also currently no way to add or remove entities, or add or remove their components, from within a `System`. As above, this doesn't actually limit what you can do with the ECS, it just means it's slightly less convenient; rather than modifying entities directly in the system, you'll need to store the modifications you want to make in the system's state, and after execution run the modifications on the `World`.

You may have also noticed that this crate is not past version `1.0.0`. The versioning follows [semver](https://semver.org/), and as such, the public API is not considered stable. The API can and will change as development continues. I won't purposefully make breaking changes, but I can't guarantee that, when I release version `0.7.0`, it will be absolutely painless to upgrade. Note that this is not unique to `brood`; *none* of the ECS crates on [arewegameyet](https://arewegameyet.rs/ecosystem/ecs/) are past version `1.0.0`, and therefore none of them promise a stable API.

Hopefully that answers your question :)
